// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieScore;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MSContext))]
    [Migration("20241112023919_SeedMovies2")]
    partial class SeedMovies2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MovieScore.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("Movie_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MovieScore.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Release")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Writers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 912649,
                            Actors = "Tom Hardy, Michelle Williams",
                            Description = "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
                            Director = "Tim Scott",
                            Path = "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
                            Rating = 6.5,
                            Release = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Venom: The Last Dance",
                            Type = "movie",
                            Writers = "David White"
                        },
                        new
                        {
                            Id = 1118031,
                            Actors = "Raúl Jiménez, Ana María Rivas",
                            Description = "When a kind of rabies that transforms people into aggressive creatures spreads across the planet, Manel isolates himself at home with his cat, relying on his wits to survive; but soon they must go out in search of food, by land and by sea, dodging many dangers.",
                            Director = "Carlos Muñoz",
                            Path = "/wIGJnIFQlESkC2rLpfA8EDHqk4g.jpg",
                            Rating = 6.9000000000000004,
                            Release = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Apocalypse Z: The Beginning of the End",
                            Type = "movie",
                            Writers = "Luis Hernández"
                        },
                        new
                        {
                            Id = 533535,
                            Actors = "Ryan Reynolds, Hugh Jackman",
                            Description = "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
                            Director = "David Leitch",
                            Path = "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
                            Rating = 7.7000000000000002,
                            Release = new DateTime(2024, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Deadpool & Wolverine",
                            Type = "movie",
                            Writers = "Rhett Reese, Paul Wernick"
                        },
                        new
                        {
                            Id = 1051896,
                            Actors = "Ethan Hawke, Jack Dylan Grazer",
                            Description = "In the near future, on a decimated Earth, Paul and his twin sons face terror at night when ferocious creatures awaken. When Paul is nearly killed, the boys come up with a plan for survival, using everything their father taught them to keep him alive.",
                            Director = "Mark Johnson",
                            Path = "/spWV1eRzlDxvai8LbxwAWR0Vst4.jpg",
                            Rating = 6.0,
                            Release = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Arcadian",
                            Type = "movie",
                            Writers = "Chris Davis"
                        },
                        new
                        {
                            Id = 845781,
                            Actors = "Dwayne Johnson, Chris Evans",
                            Description = "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous bounty hunter in a globe-trotting, action-packed mission to save Christmas.",
                            Director = "Jake Kasdan",
                            Path = "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
                            Rating = 6.9000000000000004,
                            Release = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Red One",
                            Type = "movie",
                            Writers = "Chris Morgan"
                        },
                        new
                        {
                            Id = 1084736,
                            Actors = "Jim Caviezel, Guy Pearce",
                            Description = "Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.",
                            Director = "Kevin Reynolds",
                            Path = "/zw4kV7npGtaqvUxvJE9IdqdFsNc.jpg",
                            Rating = 8.3000000000000007,
                            Release = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "The Count of Monte-Cristo",
                            Type = "movie",
                            Writers = "Alexandre Dumas"
                        },
                        new
                        {
                            Id = 335983,
                            Actors = "Tom Hardy, Michelle Williams",
                            Description = "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
                            Director = "Ruben Fleischer",
                            Path = "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
                            Rating = 6.7999999999999998,
                            Release = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Venom",
                            Type = "movie",
                            Writers = "Jeff Pinkner, Scott Rosenberg"
                        },
                        new
                        {
                            Id = 580489,
                            Actors = "Tom Hardy, Woody Harrelson",
                            Description = "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
                            Director = "Andy Serkis",
                            Path = "/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg",
                            Rating = 6.7999999999999998,
                            Release = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Venom: Let There Be Carnage",
                            Type = "movie",
                            Writers = "Kelly Marcel"
                        },
                        new
                        {
                            Id = 519182,
                            Actors = "Steve Carell, Taraji P. Henson",
                            Description = "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
                            Director = "Kyle Balda",
                            Path = "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
                            Rating = 7.0999999999999996,
                            Release = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Despicable Me 4",
                            Type = "movie",
                            Writers = "Matthew Fogel"
                        },
                        new
                        {
                            Id = 1196470,
                            Actors = "Nicolas Duvauchelle, Mélanie Thierry",
                            Description = "A couple celebrates their son’s birthday in the middle of the ocean on their boat. A violent storm hits and it brings up hungry creatures from the depths and they fight for their survival.",
                            Director = "Éric Rochant",
                            Path = "/7fR3KxswtY8OHHZuOUB9td58CRX.jpg",
                            Rating = 5.0,
                            Release = new DateTime(2024, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Survive",
                            Type = "movie",
                            Writers = "Éric Rochant"
                        },
                        new
                        {
                            Id = 1094974,
                            Actors = "Sophie Turner, Matthew Goode",
                            Description = "A burned-out professional sniper finds himself trapped in an all-glass penthouse by a lethal competitor and must find a way to survive and escape with little to no cover between him and the killer.",
                            Director = "Tom Paton",
                            Path = "/xNLiMNyFzKTL9PVIEulG55Hei8j.jpg",
                            Rating = 6.5999999999999996,
                            Release = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Take Cover",
                            Type = "movie",
                            Writers = "Tom Paton"
                        },
                        new
                        {
                            Id = 976734,
                            Actors = "Jessica Chastain, John Boyega",
                            Description = "Top level CIA agent Avery Graves is blackmailed by terrorists into betraying her own country to save her kidnapped husband. Cut off from her team, she turns to her underworld contacts to survive and help locate the coveted intelligence that the kidnappers want.",
                            Director = "Mark Williams",
                            Path = "/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg",
                            Rating = 6.2999999999999998,
                            Release = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tag = "action",
                            Title = "Canary Black",
                            Type = "movie",
                            Writers = "Mark Williams"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
